export const DEFAULT_INVESTMENT_PLANS = [
  {
    id: "PLAN-800",
    name: "Plan 1",
    price: 800,
    riseCoins: 5,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "5 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-1200",
    name: "Plan 2",
    price: 1200,
    riseCoins: 8,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "8 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-1800",
    name: "Plan 3",
    price: 1800,
    riseCoins: 12,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "12 Rise Coins on approval",
      "Build your referral team",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-2500",
    name: "Plan 4",
    price: 2500,
    riseCoins: 17,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "17 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: true,
    active: true,
  },
  {
    id: "PLAN-3500",
    name: "Plan 5",
    price: 3500,
    riseCoins: 23,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "23 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-4500",
    name: "Plan 6",
    price: 4500,
    riseCoins: 30,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "30 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-5500",
    name: "Plan 7",
    price: 5500,
    riseCoins: 40,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "40 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-7000",
    name: "Plan 8",
    price: 7000,
    riseCoins: 52,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "52 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-8500",
    name: "Plan 9",
    price: 8500,
    riseCoins: 65,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "65 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-10000",
    name: "Plan 10",
    price: 10000,
    riseCoins: 80,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "80 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
] as const;

export const DEFAULT_REFERRAL_RULES = {
  level1Percent: 48,
  level2Percent: 18,
  level3Percent: 10,
} as const;

export const DEFAULT_REFERRAL_RISE_COINS_RULES = {
  level1Percent: 100,
  level2Percent: 100,
  level3Percent: 100,
} as const;

// Referral tiers are exposed to the frontend so it can explain the active rank ladder.
export const DEFAULT_REFERRAL_TIERS = [
  { title: "Starter", riseCoinsRequired: 30, directPercent: 28, indirectPercent: 16, teamPercent: 0 },
  { title: "Vision", riseCoinsRequired: 1000, directPercent: 30, indirectPercent: 16, teamPercent: 0 },
  { title: "Elevate", riseCoinsRequired: 4000, directPercent: 33, indirectPercent: 16, teamPercent: 3 },
  { title: "Sapphire", riseCoinsRequired: 8000, directPercent: 35, indirectPercent: 16, teamPercent: 4 },
  { title: "Ruby", riseCoinsRequired: 20000, directPercent: 37, indirectPercent: 17, teamPercent: 5 },
  { title: "Diamond", riseCoinsRequired: 50000, directPercent: 39, indirectPercent: 17, teamPercent: 6 },
  { title: "Platinum", riseCoinsRequired: 120000, directPercent: 41, indirectPercent: 18, teamPercent: 7 },
  { title: "Elite", riseCoinsRequired: 250000, directPercent: 43, indirectPercent: 18, teamPercent: 8 },
  { title: "Royal", riseCoinsRequired: 400000, directPercent: 46, indirectPercent: 18, teamPercent: 9 },
  { title: "Imperial", riseCoinsRequired: 500000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
] as const;
export const DEFAULT_REWARD_MILESTONES = [
  { riseCoinsRequired: 30, rewardAmount: 0, title: "Level 1" },
  { riseCoinsRequired: 1000, rewardAmount: 5000, title: "Level 2" },
  { riseCoinsRequired: 4000, rewardAmount: 12000, title: "Level 3" },
  { riseCoinsRequired: 8000, rewardAmount: 20000, title: "Level 4" },
  { riseCoinsRequired: 20000, rewardAmount: 35000, title: "Level 5" },
] as const;

export const DEFAULT_WITHDRAWAL_RULES = {
  minimumAmount: 500,
  taxPercent: 10,
  dailyLimitMin: 5000,
  dailyLimitMax: 5000,
  processingHoursMin: 24,
  processingHoursMax: 48,
} as const;
