export const DEFAULT_INVESTMENT_PLANS = [
  {
    id: "PLAN-1000",
    name: "Plan 1",
    price: 1000,
    points: 6,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "6 reward points on approval",
      "No Courses",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-2000",
    name: "Plan 2",
    price: 2000,
    points: 12,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "12 reward points on approval",
      "No Courses",
      "Build your referral team",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-4000",
    name: "Plan 3",
    price: 4000,
    points: 30,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "30 reward points on approval",
      "5 Courses (2 Mandatory + 3 Choice)",
      "Eligible for 3-level referral income",
    ],
    featured: true,
    active: true,
  },
  {
    id: "PLAN-6500",
    name: "Plan 4",
    price: 6500,
    points: 44,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "44 reward points on approval",
      "10 Courses (2 Mandatory + 8 Choice)",
      "Eligible for 3-level referral income",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-9500",
    name: "Plan 5",
    price: 9500,
    points: 63,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "63 reward points on approval",
      "15 Courses (3 Mandatory + 12 Choice)",
      "Eligible for 3-level referral income",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-12000",
    name: "Plan 6",
    price: 12000,
    points: 80,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "80 reward points on approval",
      "25 Courses (3 Mandatory + 22 Choice)",
      "Eligible for 3-level referral income",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-15000",
    name: "Plan 7",
    price: 15000,
    points: 100,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "100 reward points on approval",
      "35+ Courses (All Access)",
      "Eligible for 3-level referral income",
    ],
    featured: false,
    active: true,
  },
] as const;

export const DEFAULT_REFERRAL_RULES = {
  level1Percent: 48,
  level2Percent: 18,
  level3Percent: 10,
} as const;
// Referral tiers are exposed to the frontend so it can explain the active rank ladder.
export const DEFAULT_REFERRAL_TIERS = [
  { title: "Starter", pointsRequired: 30, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Vision", pointsRequired: 1000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Elevate", pointsRequired: 4000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Sapphire", pointsRequired: 8000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Ruby", pointsRequired: 20000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Diamond", pointsRequired: 50000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Platinum", pointsRequired: 120000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Elite", pointsRequired: 250000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Royal", pointsRequired: 400000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
  { title: "Imperial", pointsRequired: 500000, directPercent: 48, indirectPercent: 18, teamPercent: 10 },
] as const;
export const DEFAULT_REWARD_MILESTONES = [
  { pointsRequired: 30, rewardAmount: 0, title: "Level 1" },
  { pointsRequired: 1000, rewardAmount: 5000, title: "Level 2" },
  { pointsRequired: 4000, rewardAmount: 12000, title: "Level 3" },
  { pointsRequired: 8000, rewardAmount: 20000, title: "Level 4" },
  { pointsRequired: 20000, rewardAmount: 35000, title: "Level 5" },
] as const;

export const DEFAULT_WITHDRAWAL_RULES = {
  minimumAmount: 500,
  taxPercent: 10,
  dailyLimitMin: 5000,
  dailyLimitMax: 5000,
  processingHoursMin: 24,
  processingHoursMax: 48,
} as const;
