export const DEFAULT_INVESTMENT_PLANS = [
  {
    id: "PLAN-800",
    name: "Plan 1",
    price: 800,
    riseCoins: 5,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "5 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-1200",
    name: "Plan 2",
    price: 1200,
    riseCoins: 8,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "8 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-1800",
    name: "Plan 3",
    price: 1800,
    riseCoins: 12,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "12 Rise Coins on approval",
      "Build your referral team",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-2500",
    name: "Plan 4",
    price: 2500,
    riseCoins: 17,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "17 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: true,
    active: true,
  },
  {
    id: "PLAN-3500",
    name: "Plan 5",
    price: 3500,
    riseCoins: 23,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "23 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-4500",
    name: "Plan 6",
    price: 4500,
    riseCoins: 30,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "30 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-5500",
    name: "Plan 7",
    price: 5500,
    riseCoins: 40,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "40 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-7000",
    name: "Plan 8",
    price: 7000,
    riseCoins: 52,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "52 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-8500",
    name: "Plan 9",
    price: 8500,
    riseCoins: 65,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "65 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
  {
    id: "PLAN-10000",
    name: "Plan 10",
    price: 10000,
    riseCoins: 80,
    level1Percent: 48,
    level2Percent: 18,
    level3Percent: 10,
    benefits: [
      "80 Rise Coins on approval",
      "Eligible for 3-level referral income",
      "Counts toward rank rewards",
    ],
    featured: false,
    active: true,
  },
] as const;

export const DEFAULT_REFERRAL_RULES = {
  level1Percent: 48,
  level2Percent: 18,
  level3Percent: 10,
} as const;

export const DEFAULT_REFERRAL_RISE_COINS_RULES = {
  level1Percent: 100,
  level2Percent: 100,
  level3Percent: 100,
} as const;

// Referral tiers are exposed to the frontend so it can explain the active rank ladder.
export const DEFAULT_REFERRAL_TIERS = [
  { title: "Starter", riseCoinsRequired: 300, directPercent: 30, indirectPercent: 8, teamPercent: 0 },
  { title: "Bronze", riseCoinsRequired: 600, directPercent: 30, indirectPercent: 9, teamPercent: 0 },
  { title: "Silver", riseCoinsRequired: 1000, directPercent: 32, indirectPercent: 9, teamPercent: 5 },
  { title: "Gold", riseCoinsRequired: 1300, directPercent: 33, indirectPercent: 10, teamPercent: 6 },
  { title: "Platinum", riseCoinsRequired: 1600, directPercent: 34, indirectPercent: 11, teamPercent: 7 },
  { title: "Diamond", riseCoinsRequired: 2000, directPercent: 35, indirectPercent: 11, teamPercent: 8 },
  { title: "Elite", riseCoinsRequired: 4000, directPercent: 36, indirectPercent: 12, teamPercent: 9 },
  { title: "Royal", riseCoinsRequired: 8000, directPercent: 37, indirectPercent: 12, teamPercent: 10 },
  { title: "Master", riseCoinsRequired: 15000, directPercent: 38, indirectPercent: 13, teamPercent: 10 },
  { title: "Superior", riseCoinsRequired: 25000, directPercent: 39, indirectPercent: 13, teamPercent: 10 },
  { title: "Champion", riseCoinsRequired: 50000, directPercent: 40, indirectPercent: 13, teamPercent: 10 },
  { title: "Ultimate", riseCoinsRequired: 100000, directPercent: 40, indirectPercent: 14, teamPercent: 10 },
] as const;
export const DEFAULT_REWARD_MILESTONES = [
  { riseCoinsRequired: 300, rewardAmount: 1000, title: "Starter" },
  { riseCoinsRequired: 600, rewardAmount: 1500, title: "Bronze" },
  { riseCoinsRequired: 1000, rewardAmount: 2000, title: "Silver" },
  { riseCoinsRequired: 1300, rewardAmount: 2500, title: "Gold" },
  { riseCoinsRequired: 1600, rewardAmount: 3500, title: "Platinum" },
  { riseCoinsRequired: 2000, rewardAmount: 5000, title: "Diamond" },
  { riseCoinsRequired: 4000, rewardAmount: 7000, title: "Elite" },
  { riseCoinsRequired: 8000, rewardAmount: 10000, title: "Royal" },
  { riseCoinsRequired: 15000, rewardAmount: 12000, title: "Master" },
  { riseCoinsRequired: 25000, rewardAmount: 18000, title: "Superior" },
  { riseCoinsRequired: 50000, rewardAmount: 23000, title: "Champion" },
  { riseCoinsRequired: 100000, rewardAmount: 30000, title: "Ultimate" },
] as const;

export const DEFAULT_WITHDRAWAL_RULES = {
  minimumAmount: 500,
  taxPercent: 10,
  dailyLimitMin: 5000,
  dailyLimitMax: 5000,
  processingHoursMin: 24,
  processingHoursMax: 48,
} as const;
